import css from "./Grid.module.css";

function Grid({ active, color, position }) {
  return (
    <div
      className={`${css.gridContainer} ${
        active ? css.gridActive : css.gridInactive
      }`}
      style={{ [position]: "0" }}
    >
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />

      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
      <div className={css.gridItem} style={{ backgroundColor: color }} />
    </div>
  );
}

export default Grid;
