import React from "react";

import css from "./Grid.module.css";

const Grid = ({ active, color, position }) => {
  return (
    <div
      className={`${css.container} ${
        active ? css.gridActive : css.gridInactive
      }`}
      style={{ [position]: "0" }}
    >
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>

      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
      <div className={css.gridItem} style={{ backgroundColor: color }}></div>
    </div>
  );
};

export default Grid;
