import "./Grid.scss";

const Grid = ({ active, color, position }) => {
  return (
    <div
      className={`grid-container ${active ? "grid-active" : "grid-inactive"}`}
      style={{ [position]: "0" }}
    >
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />

      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
      <div className="grid-item" style={{ backgroundColor: color }} />
    </div>
  );
};

export default Grid;
